#!/usr/bin/env bash
set -e
unset DB_ROOT_PASSWORD
unset DRUPAL_DEFAULT_ACCOUNT_PASSWORD OJS_ADMIN_PASSWORD \
  OMEKA_CLASSIC_ADMIN_PASSWORD OMEKA_S_ADMIN_PASSWORD WORDPRESS_ADMIN_PASSWORD
exec s6-notifyoncheck -d -t 30000 -n 1 /usr/sbin/php-fpm83 \
	--pid /run/php-fpm/php-fpm.pid \
	--prefix /run/php-fpm \
	--fpm-config /etc/php83/php-fpm.conf
